New companies table seeded by Pablo
itsalwaysbenny/makersglassdoor pull request #7
Opened 2018-02-09 13:47 UTC by sunali1

2018-02-09 14:07 UTC, BertZZ requested changes

2018-02-09 14:07 UTC, BertZZ commented on test.js
> +};
Can we put this file somewhere on the server side instead of having it float in the ether.

2018-02-09 14:07 UTC, BertZZ commented on node-server/db/seeds/development/users_reviews_seed.js
> +
Remove this commented out code

2018-02-09 14:07 UTC, BertZZ commented on node-server/db/seeds/development/users_reviews_seed.js
> +// };
And all this

2018-02-09 14:07 UTC, BertZZ commented on node-server/db/seeds/development/users_reviews_seed.js
> +
Blank lines

2018-02-09 14:07 UTC, BertZZ commented on node-server/knexfile.js
> +
Huh?

2018-02-12 11:05 UTC, Pablo123GitHub commented
closing because the changes have been made in a different PR. thanks

2018-02-12 11:05 UTC, closed without merging